.PHONY: secrets doctor build up public status test usage security down

secrets:
	./scripts/generate_secrets.sh

doctor:
	./scripts/doctor.sh

build:
	./scripts/build.sh

up:
	./scripts/up_local.sh

public:
	./scripts/up_public.sh

status:
	./scripts/status.sh

test:
	./scripts/test_gateway.sh

usage:
	./scripts/token_report.sh

security:
	./scripts/security_smoke_test.sh

down:
	./scripts/down.sh
